### ISSUE TITLE
Large image won't crop

### ISSUE THREAD

**Issue by Rude-Monkey** [naver/android-imagecropview#16]
Hi Helloyako, 

I get a very strange result when trying to crop large images (most of the pictures I took with the phone's camera) :
- In most cases the app will simply crash and but looking at the logs, it is because of an OOM error ("Failed to allocate a 63489036 byte allocation with 11027464 free bytes and 10MB until OOM" for a 2MB image).
- In other cases the app wil crash because of an illegal argument exception : 
  
  java.lang.IllegalArgumentException: height must be > 0
           at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:446)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:791)
           at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:62)
           at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:36)
           at com.naver.android.helloyako.imagecrop.view.ImageCropViewBase.getCroppedImage(ImageCropViewBase.java:966)
           at com.example.vincent.osmtest1.CropActivity$1.onClick(CropActivity.java:120)
           at android.view.View.performClick(View.java:5697)
           at android.widget.TextView.performClick(TextView.java:10826)
           at android.view.View$PerformClick.run(View.java:22526)
           at android.os.Handler.handleCallback(Handler.java:739)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:158)
           at android.app.ActivityThread.main(ActivityThread.java:7224)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
- In rare cases it wil "work" : the app won't crash but the cropped image's width will be the same as the crop rectangle's but it's height will be the same as the original one (I'm only using 1:1 ratio in order to display square images once cropped.
- In VERY rare cases it will work fine but a log will still show up and tell there was an OOM error (but not fatal)
- For small images the crop action works just fine =)

I know you already encountered some on these issues but since they were fixed I have absolutely no idea why this is happening.

**Comment by helloyako** [comment]
@MasterTrollVG78 
Hello, Nice to meet you :)

Is this sample app problem?

**Comment by joeytheman** [comment]
Try adding

```
android:largeHeap="true"
```

to your

```
<application
    android:largeHeap="true"
></application>
```

in `AndroidManifest.xml`

**Comment by helloyako** [comment]
if issue were continue, reopen please.
