### ISSUE TITLE
[Crash] IllegalArgumentException

### ISSUE THREAD

**Issue by helloyako** [naver/android-imagecropview#2]
```
java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
    at android.graphics.Bitmap.createBitmap(Bitmap.java:760)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:724)
    at com.naver.android.helloyako.imagecrop.view.ImageCropViewBase.getCroppedImage(ImageCropViewBase.java:954)
    at com.naver.android.pholar.ratio.PhotoRatioActivity$1.onClick(PhotoRatioActivity.java:88)
    at android.view.View.performClick(View.java:4630)
    at android.view.View$PerformClick.run(View.java:19339)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5335)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by helloyako** [comment]
resolve in v1.0.1
