### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryErro

### ISSUE THREAD

**Issue by mujahid-sagoon** [naver/android-imagecropview#29]
Getting this crash from crashlytics dashboard.
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 59064332 byte allocation with 4193552 free bytes and 48MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:728)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:653)
       at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:69)
       at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:43)
       at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:34)
       at com.naver.android.helloyako.imagecrop.view.ImageCropView.getCroppedImage(ImageCropView.java:927)
       at com.sagoon.connect.share.earn.dashboard.newDashboard.DashboardImageResizerActivity.onClick(DashboardImageResizerActivity.java:57)
       at android.view.View.performClick(View.java:5272)
       at android.view.View$PerformClick.run(View.java:21528)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5790)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by helloyako** [comment]
Hello :)

Did you add `android:largeHeap="true"` in an AndroidManifest.xml ?
