### ISSUE TITLE
OutOfMemory 

### ISSUE THREAD

**Issue by muratYamann** [naver/android-imagecropview#31]
in Manifest :  android:largeHeap="true"

Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:625)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:551)
       at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:69)
       at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:43)
       at com.naver.android.helloyako.imagecrop.model.CropInfo.getCroppedImage(CropInfo.java:34)
       at com.naver.android.helloyako.imagecrop.view.ImageCropView.getCroppedImage(ImageCropView.java:927)
       at com.modacruz2.app.addProduct.ImageGalleryFragment.getCroppedImages(ImageGalleryFragment.java:188)
       at com.modacruz2.app.addProduct.ImagePickerActivity$3.run(ImagePickerActivity.java:113)
       at java.lang.Thread.run(Thread.java:841)

@helloyako

**Comment by helloyako** [comment]
Did you see that? #24

**Comment by helloyako** [comment]
How did you set image?
I recommend`imageCropView.setImageFilePath(path);` instead of `imageCropView.setImageURI(imageUri);`
